### PR TITLE
Multiple tables

### PR DESCRIPTION
**Pull request by TuyishimireEric**
# Multiple tables
In this project I added new tables and added foreign key columns to the animals table to model one-to-many relationships. Afterward, I used JOIN to query the data.

## Highlights and sreenshots

- [x]  Created a table named owners
- [x] Created a table named specie
- [x] Modified animals table
- [x] Inserted data into the owners table
- [x] Inserted data into the species table
- [x] Modified inserted animals so it includes the species_id value
- [x] Modified inserted animals to include owner information (owner_id) 
- [x] I have written queries (using JOIN) to answer the following questions
>What animals belong to Melody Pond?
>image
>List of all animals that are pokemon (their type is Pokemon).
>image
>List all owners and their animals, remember to include those that don't own any animal.
>image
>How many animals are there per species?
>image
>List all Digimon owned by Jennifer Orwell.
>image
>List all animals owned by Dean Winchester that haven't tried to escape.
>image
>Who owns the most animals?
>image

***CHEERS AND HAPPY REVIEWING! :joy_cat:***

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @TuyishimireEric ✋, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 

## Highlights 💪 

- correct git-flow is used
- good PR


## Required Changes ♻️

- [ ] Good jobs so far 👏. It would be better if you add all your queries to answer various questions in the `queries.sql` file as it is among project requirements too 😉 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
Thank you @BertrandConxy for reviewing my project, I have forgotten to add these queries. 
I am going to add them in queries.sql, Thank you!

**Comment by BertrandConxy** [comment]
You are welcome 😎. Also feel free to connect with me for further assistance

**Comment by TuyishimireEric** [comment]
Thank you

**Review by phelian23 — APPROVED** [review]
Hi @TuyishimireEric,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly
✅ No linter error
✅ Good descriptive PR 👍
✅ Good commit messages 👍

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TuyishimireEric** [comment]
Thank you @phelian23 for approving my project

**Pull request merged**
